version: '2'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit

  redis:
    image: redis:3.2.3
    ports:
      - 6379:6379

  server:
    image: shipperizer/reimagined-garbanzo:latest
    build: .
    command: supervisord -c /var/app/server.conf
    links:
      - rabbitmq:rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=rabbit
      - RABBITMQ_PASS=rabbit
    depends_on:
      - rabbitmq

  client:
    image: shipperizer/reimagined-garbanzo:latest
    build: .
    links:
      - rabbitmq:rabbitmq
      - redis:redis_host
    command: supervisord -c /var/app/client.conf
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=rabbit
      - RABBITMQ_PASS=rabbit
      - C_FORCE_ROOT=true
    depends_on:
      - server
      - redis

  beat:
    image: shipperizer/reimagined-garbanzo:latest
    build: .
    links:
      - rabbitmq:rabbitmq
      - redis:redis_host
    command: make beat
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=rabbit
      - RABBITMQ_PASS=rabbit
      - C_FORCE_ROOT=true
    depends_on:
      - server
      - redis
