version: '2'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
      - RABBITMQ_SSL_CACERTFILE=/tmp/ca/cacert.pem
      - RABBITMQ_SSL_CERTFILE=/tmp/server/cert.pem
      - RABBITMQ_SSL_KEYFILE=/tmp/server/key.pem
    volumes:
      - ./server/cert.pem:/tmp/server/cert.pem
      - ./server/key.pem:/tmp/server/key.pem
      - ./testca/cacert.pem:/tmp/ca/cacert.pem

  redis:
    image: redis:3.2.3
    ports:
      - 6379:6379

  server:
    image: shipperizer/reimagined-garbanzo:latest
    build: .
    command: supervisord -c /var/app/server.conf
    links:
      - rabbitmq:rabbitmq
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=rabbit
      - RABBITMQ_PASS=rabbit
    depends_on:
      - rabbitmq
    volumes:
      - ./client/cert.pem:/tmp/client/cert.pem
      - ./client/key.pem:/tmp/client/key.pem
      - ./testca/cacert.pem:/tmp/ca/cacert.pem

  client:
    image: shipperizer/reimagined-garbanzo:latest
    build: .
    links:
      - rabbitmq:rabbitmq
      - redis:redis_host
    command: supervisord -c /var/app/client.conf
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=rabbit
      - RABBITMQ_PASS=rabbit
      - C_FORCE_ROOT=true
    depends_on:
      - server
      - redis
      - beat
    volumes:
      - ./client/cert.pem:/tmp/client/cert.pem
      - ./client/key.pem:/tmp/client/key.pem
      - ./testca/cacert.pem:/tmp/ca/cacert.pem

  beat:
    image: shipperizer/reimagined-garbanzo:latest
    build: .
    links:
      - rabbitmq:rabbitmq
      - redis:redis_host
    command: supervisord -c /var/app/beat.conf
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=rabbit
      - RABBITMQ_PASS=rabbit
      - C_FORCE_ROOT=true
    depends_on:
      - server
      - redis
    volumes:
      - ./client/cert.pem:/tmp/client/cert.pem
      - ./client/key.pem:/tmp/client/key.pem
      - ./testca/cacert.pem:/tmp/ca/cacert.pem
